### ISSUE TITLE
collectCookieMiddleware пытается установить заголовок на отправленный ответ

### ISSUE THREAD

**Issue by krutoo** [sima-land/isomorph#31]
#### Ситуация

В Node.js в рамках ответа на входящий запрос мы запускаем саги в которых выполняются исходящие запросы.

В случае когда сага обрубается по таймауту те саги которые уже были запущены продолжают выполняться.

В результате выполняется промежуточный слой сбора cookie (`collectCookieMiddleware`).

Так как ответ на входящий запрос уже отправлен возникает ошибка `Cannot set headers after they are sent to the client`.

#### Необходимо

Прежде всего необходимо добавить проверку в `collectCookieMiddleware` (как вариант проверять `res.writableEnded`)

Однако будет правильным также доработать механизм который останавливает запущенные саги.

Как вариант можно добавить опцию - стратегию остановки.

Сейчас используется `store.dispatch(END)`. Он не останавливает уже запущенные саги.

Можно добавить обертку над передаваемой в `run()` сагой которая бы вызывала fork и останавливала его если достигнут заданный таймаут.

**Comment by barabaiiika** [comment]
Тут есть еще один нюанс - даже если отменять саги, то запросы на api, выполненные из них, отменены не будут - мидлвари все равно отработают тогда. По идее, надо при отмене саг/таймауте отменять axios запросы через AbortController (кстати нужно еще посмотреть, как себя поведут мидлвари при этом, ранее мы такое вроде не делали)

**Comment by krutoo** [comment]
@barabaiiika Отменять исходящие запросы сразу решили что не будем, так как в таком случае будут логироваться ошибки отмены

В будущем также есть мысли передать мидлвари на интерспеторы
